### ISSUE TITLE
in response list of images is badly formated

### ISSUE THREAD

**Issue by denimsahu** [PlatziLabs/fake-api-backend#26]
**Describe the bug**
when filtered category by id 1 that is  Clothes category it's response data return badly formatted images list
"images": [
        "[\"https://i.imgur.com/QkIa5tT.jpeg\"",
        "\"https://i.imgur.com/jb5Yu0h.jpeg\"",
        "\"https://i.imgur.com/UlxxXyG.jpeg\"]"
    ],

**Expected behavior**
a few days ago images list was alright something like this
"images":["https://i.imgur.com/QkIa5tT.jpeg","https://i.imgur.com/jb5Yu0h.jpeg","https://i.imgur.com/UlxxXyG.jpeg"],"

**Comment by ixtk** [comment]
Looks like it doesn't parse JSON correctly on the server side. A temporary workaround would be to do

```js
product.images[0].startsWith("[") ? JSON.parse(product.images[0]) : product.images[0] : 
```

when displaying any single image on the frontend
